### ISSUE TITLE
支障がなければprivateリポジトリにしたほうが良いと思います

### ISSUE THREAD

**Issue by MattyaDaihuku** [dhidoo/ginzaforward#1]
GitHub Pagesだと強制的にPublicリポジトリになってしまうのでCloudflare Pagesがおすすめです....
Cloudflare PagesだとPrivateリポジトリでページを公開できます
部外者が失礼しました
(いつも見てます！)

**Comment by daidoshiba** [comment]
抹茶大福さま


Cloudflare Pagesに移そうと思います。

ご親切にメールをありがとうございます🙇


daido

2024年12月19日(木) 15:05 MattyaDaihuku ***@***.***>:
